[package]
name = "redis-strategy-pattern"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = "0.32.5"
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.9.2"

[[bench]]
name = "redis_strategy_bench"
harness = false

