[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.217", features = ["derive"] }
gcd-core = { version = "0.1.0", path = "../gcd-core" }
