[package]
name = "aes-encrypt"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
rand = "0.8.5"
zeroize = "1.8.1"
