[package]
name = "load-balancer"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.85"
pingora = { version = "0.4.0", features = ["lb"] }
pingora-core = "0.4.0"
pingora-load-balancing = "0.4.0"
pingora-proxy = "0.4.0"
